/**
 * Machine-readable inventory of the public Ares documentation tree.
 *
 * This catalog is intentionally separate from AresFeatureRegistry.  The
 * registry describes the small set of capabilities currently wired into the
 * runtime, while this file describes the complete documented surface so that
 * missing parser/runtime/persistence work remains visible.
 *
 * The documentation paths are relative to the official Ares-docs repository:
 * https://github.com/Ares-Developers/Ares-docs
 */

export type AresCapabilityStatus = "missing" | "partial" | "complete";
export type AresVerificationStatus = "unverified" | "synthetic" | "integration" | "target-content";
export type AresDocumentationCategory = "new" | "restored" | "bugfix" | "ui";

export interface AresCapability {
    id: string;
    title: string;
    category: AresDocumentationCategory;
    sourceDocuments: readonly string[];
    documentedKeys: readonly string[];
    documentedSections: readonly string[];
    parserStatus: AresCapabilityStatus;
    normalizedModelStatus: AresCapabilityStatus;
    runtimeStatus: AresCapabilityStatus;
    aiStatus: AresCapabilityStatus;
    presentationStatus: AresCapabilityStatus;
    saveLoadStatus: AresCapabilityStatus;
    multiplayerStatus: AresCapabilityStatus;
    deterministic: boolean;
    verificationStatus: AresVerificationStatus;
    tests: readonly string[];
    dependencies: readonly string[];
    targetModUsage: "unknown" | "required" | "optional" | "not-applicable";
    notes?: string;
}

export interface AresDocumentationDocument {
    path: string;
    category: AresDocumentationCategory;
    capabilityId: string;
}

/** Non-capability pages are tracked separately so the leaf-document count is auditable. */
export const ARES_DOCUMENTATION_ROOTS = [
    "index.rst",
    "intro.rst",
    "comparison.rst",
    "glossary.rst",
    "todo.rst",
    "new/index.rst",
    "restored/index.rst",
    "bugfixes/index.rst",
    "ui-features/index.rst",
] as const;

const DOCUMENTATION_PATHS: readonly string[] = [
    "new/additionalarmortypesandverses.rst",
    "new/alternatetheaterart.rst",
    "new/attacheffect.rst",
    "new/avoidableinternalerrors.rst",
    "new/chronoprisons.rst",
    "new/chronoshift.rst",
    "new/customanimationandprojectilepalettes.rst",
    "new/custombuildingfoundations.rst",
    "new/customcameopalettes.rst",
    "new/customizableinsignia.rst",
    "new/customizableparachuteanimations.rst",
    "new/customizableveterancy.rst",
    "new/damageparticlesystems.rst",
    "new/destroyunitsbyemp.rst",
    "new/gunner.rst",
    "new/hardcodedunitproperties.rst",
    "new/include.rst",
    "new/infantryelectrocuted.rst",
    "new/killingdrivers.rst",
    "new/lightningrods.rst",
    "new/listlengths.rst",
    "new/looseaudiofiles.rst",
    "new/makeinfantryowner.rst",
    "new/miscellaneousmoddingenhancements.rst",
    "new/mixloadingorder.rst",
    "new/mousesha.rst",
    "new/newpoweredunitlogic.rst",
    "new/operator.rst",
    "new/pcxcameos.rst",
    "new/projectiles/attachedsystem.rst",
    "new/prerequisites.rst",
    "new/prismforwarding.rst",
    "new/radarjammers.rst",
    "new/reverseengineerlogic.rst",
    "new/secretlabs.rst",
    "new/sidescountries.rst",
    "new/solidbuildings.rst",
    "new/spybehavior.rst",
    "new/stringtableenhancements.rst",
    "new/superweapons.rst",
    "new/survivors.rst",
    "new/urbancombattrenches.rst",
    "new/warheads.rst",
    "new/weapons.rst",
    "restored/actionsellunit.rst",
    "restored/actiontogglepower.rst",
    "restored/amphibiousimagechanges.rst",
    "restored/emp.rst",
    "restored/firestormwall.rst",
    "restored/laserfences.rst",
    "restored/multiengineer.rst",
    "restored/multiengineercheckbox.rst",
    "restored/spotlights.rst",
    "restored/vehicle-thief.rst",
    "ui-features/bitmapscreenshots.rst",
    "ui-features/campaignlist.rst",
    "ui-features/campaignloadscreentextcolor.rst",
    "ui-features/commandlinearguments.rst",
    "ui-features/customizablecampaignbuttons.rst",
    "ui-features/customizabledropdowncolors.rst",
    "ui-features/graphicssurfacedrawing.rst",
    "ui-features/internalerrorsdebugging.rst",
    "ui-features/keyboardcommandshotkeys.rst",
    "ui-features/loadingscreen.rst",
    "ui-features/loneplayerskirmish.rst",
    "ui-features/menubuttoncustomization.rst",
    "ui-features/newgameresolutions.rst",
    "ui-features/randommapgenerator.rst",
    "ui-features/userinterfacecolors.rst",
    "bugfixes/type1/aitargetingcloakedobjectswithmajorsuperweapons.rst",
    "bugfixes/type1/animatedsuperweaponcursor.rst",
    "bugfixes/type1/chronoshiftwillsinkjumpjetunits.rst",
    "bugfixes/type1/enemyharvesterguardmodeexploit.rst",
    "bugfixes/type1/firingvoicesandveterancy.rst",
    "bugfixes/type1/frozenmutationmakeinfantryanimations.rst",
    "bugfixes/type1/loadscreencolors.rst",
    "bugfixes/type1/misleadingveterannavalcameos.rst",
    "bugfixes/type1/parasitesinairborneunits.rst",
    "bugfixes/type1/prismsupportbugs.rst",
    "bugfixes/type1/secretlabboonweighting.rst",
    "bugfixes/type1/temporalwarheadsandpotentialoccupationtargets.rst",
    "bugfixes/type1/temporalwarheadsearnexperiencebykillingfriendlyunits.rst",
    "bugfixes/type1/toomanysecretlabs.rst",
    "bugfixes/type1/unitsoundsplayedatinappropriatetimes.rst",
    "bugfixes/type1/warheadversesspecialvalues.rst",
    "bugfixes/type2/aircrafttypesandrailguns.rst",
    "bugfixes/type2/airtoaircombat.rst",
    "bugfixes/type2/alternatetheaterartforbuildingtypes.rst",
    "bugfixes/type2/amphibiousobjectssinkwhenchronoshiftedontowater.rst",
    "bugfixes/type2/animationdamagewarheads.rst",
    "bugfixes/type2/baseunit.rst",
    "bugfixes/type2/buildableconstructionyards.rst",
    "bugfixes/type2/buildablesecretlabs.rst",
    "bugfixes/type2/buildconst.rst",
    "bugfixes/type2/buildingtypesandinfantrytypesdonotreloadammoproperly.rst",
    "bugfixes/type2/buildingtypeupgradesarenotviableprerequisites.rst",
    "bugfixes/type2/cloakableaircrafttypesandbuildingtypes.rst",
    "bugfixes/type2/custompalettes.rst",
    "bugfixes/type2/destroyanimscausereconnectionerrors.rst",
    "bugfixes/type2/destroyanimsdontremap.rst",
    "bugfixes/type2/digsound.rst",
    "bugfixes/type2/factoryloadsharing.rst",
    "bugfixes/type2/hardcodedwallgateinteractions.rst",
    "bugfixes/type2/hijackersarereimbursedwhenaunitisgrinded.rst",
    "bugfixes/type2/infantrylostinspecialfunctionbuildings.rst",
    "bugfixes/type2/initialveterancameos.rst",
    "bugfixes/type2/ivanbombscanonlybefiredbyinfantrytypes.rst",
    "bugfixes/type2/jumpjetshadows.rst",
    "bugfixes/type2/mindcontrollerparasites.rst",
    "bugfixes/type2/miragelogicwithturretsbarrels.rst",
    "bugfixes/type2/movingalphalights.rst",
    "bugfixes/type2/multipleaifactoriescloneunits.rst",
    "bugfixes/type2/negativelydamagingweaponswithanimlist.rst",
    "bugfixes/type2/newconstructionoptions.rst",
    "bugfixes/type2/opentoppedtransportsdonotdecloaktofire.rst",
    "bugfixes/type2/overridingmissionsmdpkt.rst",
    "bugfixes/type2/pktduplication.rst",
    "bugfixes/type2/radbeamsandwavesusingthewrongflh.rst",
    "bugfixes/type2/reinforcementsandmultiplayermaptriggers.rst",
    "bugfixes/type2/remappablewalls.rst",
    "bugfixes/type2/sonicwaveambientdamage.rst",
    "bugfixes/type2/specialweaponsnowfunctioninsecondaryslots.rst",
    "bugfixes/type2/spyplanecountdecoupledfromallyparadropnum.rst",
    "bugfixes/type2/summonedairstrikesnolongerdependentonsovparadropinf.rst",
    "bugfixes/type2/temporalwarheadsstillaffectobjectsthatarenotwarpable.rst",
    "bugfixes/type2/the100unitbug.rst",
    "bugfixes/type2/unitinstancesnotcountingtowardsbuildlimit.rst",
    "bugfixes/type2/unitsoundsplayedatinappropriatetimes.rst",
    "bugfixes/type2/unitsoverpoweringbuildings.rst",
    "bugfixes/type2/vehicleparadropoffset.rst",
    "bugfixes/type3.rst",
] as const;

function categoryFor(path: string): AresDocumentationCategory {
    if (path.startsWith("new/")) return "new";
    if (path.startsWith("restored/")) return "restored";
    if (path.startsWith("ui-features/")) return "ui";
    return "bugfix";
}

function titleFor(path: string): string {
    const filename = path.slice(path.lastIndexOf("/") + 1).replace(/\.rst$/i, "");
    return filename
        .replace(/([a-z])([A-Z])/g, "$1 $2")
        .replace(/[-_]+/g, " ")
        .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

const DOCUMENTED_KEYS: Readonly<Record<string, readonly string[]>> = {
    "new/additionalarmortypesandverses.rst": ["[ArmorTypes]", "[Warhead]Versus.*", "Versus.*.ForceFire", "Versus.*.Retaliate", "Versus.*.PassiveAcquire"],
    "new/attacheffect.rst": ["AttachEffect.Animation", "AttachEffect.Duration", "AttachEffect.TemporalHidesAnim", "AttachEffect.SpeedMultiplier", "AttachEffect.ArmorMultiplier", "AttachEffect.FirepowerMultiplier", "AttachEffect.ROFMultiplier", "AttachEffect.Cloakable", "AttachEffect.ForceDecloak", "AttachEffect.DiscardOnEntry", "AttachEffect.PenetratesIronCurtain", "AttachEffect.Delay", "AttachEffect.InitialDelay", "AttachEffect.Cumulative", "AttachEffect.AnimResetOnReapply"],
    "new/chronoprisons.rst": ["[Weapon]Abductor", "[TechnoType]PassengerTurret"],
    "new/chronoshift.rst": ["[General]ChronoInfantryCrush", "[TechnoType]Chronoshift.Allow", "[BuildingType]Chronoshift.IsVehicle", "[TechnoType]Chronoshift.Crushable", "Chronosphere.ReconsiderBuildings", "Chronosphere.KillOrganic", "Chronosphere.KillTeleporters", "Chronosphere.AffectsIronCurtain", "Chronosphere.AffectsUnwarpable", "Chronosphere.AffectsUndeployable", "Chronosphere.BlowUnplaceable", "Chronosphere.KillCargo"],
    "new/customanimationandprojectilepalettes.rst": ["[Animation]CustomPalette"],
    "new/custombuildingfoundations.rst": ["Foundation=Custom", "Foundation.N", "FoundationOutline.Length", "FoundationOutline.N"],
    "new/customcameopalettes.rst": ["[UnitArt]CameoPalette", "[SuperWeapon]SidebarPalette"],
    "new/customizableinsignia.rst": ["Insignia.Rookie", "Insignia.Veteran", "Insignia.Elite", "InsigniaFrame.Rookie", "InsigniaFrame.Veteran", "InsigniaFrame.Elite", "Insignia.ShowEnemy", "[General]EnemyInsignia"],
    "new/customizableparachuteanimations.rst": ["Parachute.Anim"],
    "new/customizableveterancy.rst": ["Trainable", "Experience.FromPassengers", "Experience.PromotePassengers", "Experience.PassengerModifier", "Experience.FromAirstrike", "Experience.AirstrikeModifier", "Experience.SpawnOwnerModifier", "Experience.SpawnModifier", "Experience.MindControlSelfModifier", "Experience.MindControlVictimModifier"],
    "new/damageparticlesystems.rst": ["[TechnoType]DamageSparks", "[TechnoType]DamageSmokeParticleSystems", "[TechnoType]DamageSparksParticleSystems", "DamageParticleSystems"],
    "new/destroyunitsbyemp.rst": ["[TechnoType]EMP.Threshold"],
    "new/gunner.rst": ["IFVMode", "WeaponTurretIndexX", "WeaponUINameX", "[VehicleType]VoiceIFVRepair"],
    "new/include.rst": ["[#include]"],
    "new/killingdrivers.rst": ["[Warhead]KillDriver", "[TechnoType]ProtectedDriver", "[TechnoType]CanDrive", "[TechnoType]CanBeDriven", "[Country]CanBeDriven"],
    "new/lightningrods.rst": ["[BuildingType]LightningRod", "LightningRod.Modifier"],
    "restored/firestormwall.rst": ["Firestorm.Wall", "SubjectToFirestorm", "FirestormActiveAnim", "FirestormIdleAnim", "FirestormGroundAnim", "FirestormAirAnim", "FirestormWarhead", "DamageToFirestormDamageCoefficient"],
    "restored/vehicle-thief.rst": ["[InfantryType]VehicleThief", "VehicleThief.EnterSound", "VehicleThief.LeaveSound", "VehicleThief.KillPilots", "VehicleThief.BreakMindControl", "VehicleThief.Allowed", "VehicleThief.OneTime"],
    "new/makeinfantryowner.rst": ["MakeInfantryOwner"],
    "new/newpoweredunitlogic.rst": ["[UnitType]PoweredBy"],
    "new/operator.rst": ["[TechnoType]Operator"],
    "new/pcxcameos.rst": ["CameoPCX", "AltCameoPCX", "SidebarPCX"],
    "new/projectiles/attachedsystem.rst": ["[Projectile]AttachedSystem"],
    "new/prerequisites.rst": ["Prerequisite.RequiredTheaters", "GenericPrerequisites", "Prerequisite.StolenTechs"],
    "new/prismforwarding.rst": ["PrismForwarding", "PrismForwarding.Targets", "PrismForwarding.MaxFeeds", "PrismForwarding.MaxChainLength", "PrismForwarding.SupportModifier", "PrismForwarding.SupportWeapon"],
    "new/radarjammers.rst": ["RadarJamRadius"],
    "new/reverseengineerlogic.rst": ["ReverseEngineersVictims", "SpyEffect.UndoReverseEngineer", "CanBeReversed"],
    "new/secretlabs.rst": ["SecretLab.PossibleBoons", "SecretLab.GenerateOnCapture", "Secret.RequiredHouses", "Secret.ForbiddenHouses"],
    "new/sidescountries.rst": ["File.Flag", "File.LoadScreen", "LoadScreenText.Name", "RandomSelectionWeight", "ListIndex", "AI.PowerPlants", "ParaDrop.Types", "DefaultDisguise", "Crew", "SurvivorDivisor", "AI.BaseDefenses", "Sidebar.MixFileIndex", "Sidebar.YuriFileNames", "ToolTipColor", "EVA.Tag", "LoadingTheme", "GraphicalText.Image", "GraphicalText.Palette", "MultiplayerScore.Background", "MultiplayerScore.Palette", "MultiplayerScore.Bars", "MultiplayerScore.WinTheme", "MultiplayerScore.LoseTheme"],
    "new/solidbuildings.rst": ["[Projectile]SubjectToBuildings", "[BuildingArt]SolidHeight"],
    "new/spybehavior.rst": ["SpyEffect.Custom", "SpyEffect.ResetRadar", "SpyEffect.RevealRadar", "SpyEffect.PowerOutageDuration", "SpyEffect.StolenMoneyAmount", "SpyEffect.StolenMoneyPercentage", "SpyEffect.ResetSuperweapons", "SpyEffect.StolenTechIndex", "SpyEffect.UnitVeterancy", "SpyEffect.RevealProduction"],
    "new/superweapons.rst": ["SW.RequiredHouses", "SW.ForbiddenHouses", "SW.AuxBuildings", "SW.NegBuildings", "SW.AllowPlayer", "SW.AllowAI", "SW.Shots", "SW.AlwaysGranted", "SW.ShowCameo", "SW.TimerVisibility", "SW.Group", "SW.FireIntoShroud", "SW.AutoFire", "SW.ManualFire", "UseChargeDrain", "ChargeToDrainRatio", "SW.ChargeToDrainRatio", "SW.Unstoppable", "SW.Range", "SW.RangeMinimum", "SW.RangeMaximum", "SW.Designators", "SW.AnyDesignator", "SW.Inhibitors", "SW.AnyInhibitor", "SW.CreateRadarEvent", "SW.Deferment", "SW.PostDependent", "SW.UseAITargeting", "SW.AITargeting", "SW.AITargeting.Constraints", "SW.AITargeting.Preference", "SW.AIRequiresTarget", "SW.AIRequiresHouse", "SW.InitialReady", "SW.VirtualCharge", "Money.Amount", "Money.DrainAmount", "Money.DrainDelay", "SW.Animation", "EVA.*", "Message.*", "Text.*", "Light.*", "Lightning.*", "Nuke.*", "Dominator.*", "Chronosphere.*", "Protect.*", "Mutate.*", "ParaDrop.*", "SpyPlane.*", "SonarPulse.Delay", "Deliver.Types", "DropPod.Types", "DropPod.Minimum", "DropPod.Maximum", "DropPod.Veterancy", "DropPodWeapon", "DropPodTrailer", "EMPulse.Linked", "EMPulse.TargetSelf", "EMPulse.PulseDelay", "EMPulse.PulseBall", "EMPulse.Cannons", "EMPulseCannon"],
    "new/survivors.rst": ["Survivor.PilotCount", "Survivor.RookiePilotChance", "Survivor.VeteranPilotChance", "Survivor.ElitePilotChance", "Survivor.VeteranPassengerChance", "Survivor.ElitePassengerChance"],
    "new/urbancombattrenches.rst": ["UC.PassThrough", "UC.FatalRate", "UC.DamageMultiplier", "SubjectToTrenches", "Bunker.Raidable", "Rubble.Destroyed", "Rubble.Intact", "IsTrench", "CanBeOccupiedBy"],
    "new/warheads.rst": ["IronCurtain.Duration", "IronCurtain.Cap", "IronCurtain.Modifier", "MindControl.Permanent", "Temporal.WarpAway", "Ripple.Radius", "Deployed.Damage", "AffectsAllies", "AffectsEnemies", "Malicious", "InfDeathAnim", "PreImpactAnim"],
    "new/weapons.rst": ["[WeaponTypes]", "Beam.Color", "Beam.IsHouseColor", "Beam.Duration", "Beam.Amplitude", "Bolt.Color1", "Bolt.Color2", "Bolt.Color3", "Wave.IsLaser", "Wave.IsBigLaser", "Wave.Color", "Wave.IsHouseColor", "Wave.ReverseAgainstVehicles", "Wave.ReverseAgainstAircraft", "Wave.ReverseAgainstBuildings", "Wave.ReverseAgainstInfantry", "Wave.ReverseAgainstOthers", "IvanBomb.Warhead", "IvanBomb.Damage", "IvanBomb.Detachable", "IvanBomb.DestroysBridges", "IvanBomb.Delay", "IvanBomb.AttachSound", "IvanBomb.TickingSound", "IvanBomb.Image", "IvanBomb.FlickerRate", "IvanBomb.CanDetonateTimeBomb", "IvanBomb.CanDetonateDeathBomb", "IvanBomb.DetonateOnSell"],
    "restored/emp.rst": ["EMP.Duration", "EMP.Cap", "ImmuneToEMP", "EMP.Modifier"],
    "restored/multiengineer.rst": ["EngineerCaptureLevel", "EngineerDamage", "EngineerAlwaysCaptureTech", "EngineerDamageCursor.*"],
    "restored/multiengineercheckbox.rst": ["AllowMultiEngineer"],
    "restored/spotlights.rst": ["HasSpotlight", "Spotlight.StartHeight", "Spotlight.Distance", "Spotlight.AttachedTo", "Spotlight.DisableRed", "Spotlight.DisableGreen", "Spotlight.DisableBlue", "Spotlight.DisableColor"],
};

interface CapabilityOverride {
    capabilityId?: string;
    parserStatus?: AresCapabilityStatus;
    normalizedModelStatus?: AresCapabilityStatus;
    runtimeStatus?: AresCapabilityStatus;
    aiStatus?: AresCapabilityStatus;
    presentationStatus?: AresCapabilityStatus;
    saveLoadStatus?: AresCapabilityStatus;
    multiplayerStatus?: AresCapabilityStatus;
    deterministic?: boolean;
    verificationStatus?: AresVerificationStatus;
    tests?: readonly string[];
    dependencies?: readonly string[];
    targetModUsage?: AresCapability["targetModUsage"];
    notes?: string;
}

const OVERRIDES: Readonly<Record<string, CapabilityOverride>> = {
    "new/additionalarmortypesandverses.rst": {
        capabilityId: "ares.additional-armor-types",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "complete",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresArmor.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "unknown",
        notes: "Dynamic armor IDs and separate automatic-acquisition, retaliation, and force-fire gates are verified.",
    },
    "new/attacheffect.rst": {
        capabilityId: "ares.status-effects",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "missing", presentationStatus: "partial", saveLoadStatus: "missing", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true,
        tests: ["AresAttachEffect.test.ts", "AresAttachEffectRuntime.test.ts", "AresAttachEffectTraitBridge.test.ts", "AresAttachEffectObjectFactory.test.ts", "AresAttachEffectCombat.test.ts", "AresAttachEffectCombatCallsites.test.ts", "AresAnimationDamage.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "AttachEffect fields for TechnoTypes and Warheads are parsed and normalized; ObjectFactory registration and the generic trait cover automatic TechnoType spawn timing, renewal, protection retry, active instances, reapplication/stacking decisions, expiry, entry discard, aggregate numeric modifiers, and the generic combat callsites apply effective Speed/Armor/Firepower/ROF decisions. AttachEffect.Cloakable now grants a temporary cloak source and decloaks safely when the last source expires without removing permanent/veteran cloaking. Authored animations now attach to every techno renderable, loop with the unit, and are removed/recreated across cloak and TemporalHidesAnim transitions. Their Ares Damage, Damage.Delay, Warhead, and Weapon fields now run through the shared Warhead detonation path for attached effects. Standalone TriggerAnim and WarheadDetonate animation instances now use the same deterministic frame clock and area detonation bridge. Full transport/temporal state replay, save/load, AI, and deterministic multiplayer replay remain open.",
    },
    "new/custombuildingfoundations.rst": {
        capabilityId: "ares.custom-foundations",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "complete",
        aiStatus: "complete", presentationStatus: "partial", saveLoadStatus: "partial", multiplayerStatus: "complete",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresFoundation.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "Occupied cells and outline cells are distinct; exact placement/occupation paths are covered. The local Mental Omega 3.3.6 scan found 2,671 Foundation-related entries across 79 definitions.",
    },
    "new/customanimationandprojectilepalettes.rst": {
        capabilityId: "ares.custom-animation-palettes",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "complete",
        presentationStatus: "complete", saveLoadStatus: "complete", multiplayerStatus: "complete",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresCustomPalette.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "ObjectArt consumes explicit CustomPalette values for animation/projectile art; Theater resolves complete .pal names and the first ~~~ theater replacement. The local Mental Omega 3.3.6 scan found 541 entries in artmo.ini.",
    },
    "new/operator.rst": {
        capabilityId: "ares.operator",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "partial", presentationStatus: "partial", saveLoadStatus: "complete", multiplayerStatus: "complete",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresOperator.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "unknown",
        notes: "Specific InfantryType operators and the _ANY_ sentinel are evaluated from transport/garrison passengers. Missing operators disable movement and weapons without disabling unrelated building services; full AI/presentation parity remains open.",
    },
    "new/killingdrivers.rst": {
        capabilityId: "ares.killing-drivers",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "partial", presentationStatus: "partial", saveLoadStatus: "partial", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresKillingDrivers.test.ts"],
        dependencies: ["ares.effective-ini", "ares.operator"], targetModUsage: "unknown",
        notes: "KillDriver and ProtectedDriver are implemented through a generic driver-state trait and native owner/passenger handling. CanDrive and TechnoType/Country CanBeDriven gates feed the VehicleThief reclaim path, and RemoveVeterancy resets transferred vehicles; broader trigger/script, AI, presentation, save, and multiplayer parity remain open.",
    },
    "restored/vehicle-thief.rst": {
        capabilityId: "ares.vehicle-thief",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "partial", presentationStatus: "partial", saveLoadStatus: "partial", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresVehicleThief.test.ts"],
        dependencies: ["ares.effective-ini", "ares.killing-drivers", "ares.operator"], targetModUsage: "required",
        notes: "VehicleThief/CanDrive share a normalized hijack action path. Enemy hijack, neutral DriverKilled reclaim, TechnoType/Country CanBeDriven gates, operator passenger handling, mind-control cleanup, and absorbed-hijacker recovery/recycle state are implemented; the survivor pilot-count adapter exists but full survivor integration, building hijacks, audio, and trigger/event parity remain open. The local Mental Omega 3.3.6 scan found 271 driver/thief entries across 263 definitions.",
    },
    "new/include.rst": {
        capabilityId: "ares.effective-ini",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "complete",
        presentationStatus: "complete", saveLoadStatus: "complete", multiplayerStatus: "complete",
        verificationStatus: "synthetic", deterministic: true, tests: ["IniSourceLoader.test.ts", "AresCompatibilityScanner.test.ts"],
        dependencies: [], targetModUsage: "required",
        notes: "Depth-first include loading, duplicate/cycle/missing diagnostics, case-insensitive VFS lookup, and provenance are implemented.",
    },
    "new/prerequisites.rst": {
        capabilityId: "ares.generic-prerequisites",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "complete",
        aiStatus: "partial", presentationStatus: "partial", saveLoadStatus: "partial", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresPrerequisites.test.ts"],
        dependencies: ["ares.effective-ini", "ares.dynamic-sides-countries"], targetModUsage: "required",
        notes: "Generic groups, alternatives, negatives, stolen tech, theater requirements, and factory-owner predicates are normalized; permanent plans have a versioned production-extension codec while direct full-game snapshot integration remains open.",
    },
    "new/projectiles/attachedsystem.rst": {
        capabilityId: "ares.projectile-extensions",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        presentationStatus: "partial", saveLoadStatus: "missing", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true,
        tests: ["AresProjectileExtensions.test.ts"],
        dependencies: ["ares.effective-ini", "ares.damage-particle-systems"], targetModUsage: "required",
        notes: "AttachedSystem is parsed on projectiles and smoke-only systems use the shared authored particle image renderer while the projectile travels. Non-smoke particle behavior, save/load, and multiplayer certification remain open.",
    },
    "new/sidescountries.rst": {
        capabilityId: "ares.dynamic-sides-countries",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "partial", presentationStatus: "partial", saveLoadStatus: "partial", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresSides.test.ts", "AresCountrySelection.test.ts", "CountryIcon.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "Stable authored IDs, ordering, selection flags, provenance, and presentation metadata exist; legacy vanilla adapters still need migration.",
    },
    "new/superweapons.rst": {
        capabilityId: "ares.superweapons",
        parserStatus: "partial", normalizedModelStatus: "partial", runtimeStatus: "partial",
        aiStatus: "missing", presentationStatus: "partial", saveLoadStatus: "missing", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresSuperWeapons.test.ts", "AresSuperWeaponTargeting.test.ts", "AresSuperWeaponAvailability.test.ts", "AresSuperWeaponPresentationAdapter.test.ts", "AresSuperWeaponPresentationRuntime.test.ts", "AresSuperWeaponCharge.test.ts", "AresSuperWeaponChargeDrain.test.ts", "AresSuperWeaponDeferment.test.ts", "AresSuperWeaponPostDependent.test.ts", "AresSuperWeaponRadar.test.ts", "AresSuperWeaponAITargeting.test.ts", "AresSuperWeaponRange.test.ts", "AresUnitDelivery.test.ts", "AresSonarPulse.test.ts", "AresDropPod.test.ts", "AresBattery.test.ts", "AresHunterSeeker.test.ts"],
        dependencies: ["ares.effective-ini", "ares.target-filters"], targetModUsage: "required",
        notes: "The generic availability sub-capability has complete parser/model/runtime status for RequiredHouses, ForbiddenHouses, AuxBuildings, NegBuildings, AllowPlayer, AllowAI, Shots, AlwaysGranted, provider grant/revoke, and activation gating. The common activation path also enforces SW.RangeMinimum/Maximum against operational providers, SW.Designators/SW.AnyDesignator against owned TechnoTypes, and SW.Inhibitors/SW.AnyInhibitor against enemy target areas. SW.ShowCameo now filters the shared sidebar and SW.TimerVisibility filters the shared timer overlay by owner/alliance/enemy/observer relation. Authored SW.Animation and SW.AnimationVisibility are emitted at effect start after SW.Deferment, while SW.Sound and SW.ActivationSound use shared target-cell/activation audio events. SW.Group remains normalized for AI/action consumers. The aggregate superweapon surface remains partial for AI breadth, charge-lifecycle edge coverage, persistence, network certification, and remaining handlers. Hunter Seeker is tracked here as an Antares 3.0p1 reference capability because it is not a leaf in the current official documentation inventory.",
    },
    "restored/firestormwall.rst": {
        capabilityId: "ares.firestorm-wall",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        presentationStatus: "missing", saveLoadStatus: "partial", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresFirestorm.test.ts"],
        dependencies: ["ares.superweapon-charge-drain"], targetModUsage: "unknown",
        notes: "Firestorm wall metadata, same-owner linking, contact immolation, active-charge damage feedback, and hostile projectile interception are implemented; active/idle wall animation presentation and persistent/trigger/network state remain open.",
    },
    "restored/emp.rst": {
        capabilityId: "ares.emp",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "partial", presentationStatus: "partial", saveLoadStatus: "partial", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresEMP.test.ts"],
        dependencies: ["ares.effective-ini", "ares.warhead-effects"], targetModUsage: "unknown",
        notes: "Official EMP duration/cap counters, immunity defaults including SuperWeapon2 providers, same-owner EMP-capable-weapon TypeImmune, EMP.Modifier, veteran EMPIMMUNE, movement/attack paralysis, unloading-boundary deferral, power-output blackout, factory/production suspension, spawner/slave suspension, powered-superweapon pause, and aircraft crash entry are implemented. Sparkle presentation and full subsystem notifications remain separate.",
    },
    "new/destroyunitsbyemp.rst": {
        capabilityId: "ares.emp-threshold",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "partial", presentationStatus: "missing", saveLoadStatus: "partial", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true, tests: ["AresEMP.test.ts"],
        dependencies: ["ares.emp"], targetModUsage: "unknown",
        notes: "EMP.Threshold is normalized as yes/no/inair/integer and positive/in-air counter crossings destroy non-aircraft Technos through the normal world destruction path. Full hover/aircraft edge coverage, parachute integration, persistence, and network certification remain open.",
    },
    "new/gunner.rst": {
        capabilityId: "ares.ifv-modes",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "missing", presentationStatus: "partial", saveLoadStatus: "missing", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true,
        tests: ["AresTechnoExtensions.test.ts", "AresIfvRuntimeIntegration.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "IFVMode, 1-based WeaponTurretIndexX, WeaponUINameX, and VoiceIFVRepair are parsed and normalized; passenger changes re-evaluate the selected weapon, turret, and tooltip through the shared IFV path. Repair-voice consumption, full passenger weapon/turret parity, save/load, and multiplayer synchronization remain open.",
    },
    "new/weapons.rst": {
        capabilityId: "ares.weapon-visuals",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "missing", presentationStatus: "partial", saveLoadStatus: "missing", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true,
        tests: ["AresWeaponVisuals.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "Beam.Color/IsHouseColor/Duration/Amplitude, Bolt.Color1/2/3, Wave.IsLaser/IsBigLaser/Color/IsHouseColor/ReverseAgainst*, and standalone [WeaponTypes] names are parsed. Rad-beam timing/amplitude, electric-bolt colors, laser/sonic wave presentation, reverse-direction selection, and wave ambient damage are consumed by the shared renderer/simulation path; native wave lifecycle and multiplayer certification remain open.",
    },
    "new/chronoprisons.rst": {
        capabilityId: "ares.chrono-prisons",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "missing", presentationStatus: "partial", saveLoadStatus: "missing", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true,
        tests: ["AresChronoPrisons.test.ts", "AresChronoPrisonRuntimeDecision.test.ts", "AresChronoPrisonBridge.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "Abductor, Abductor.Temporal, Abductor.ChangeOwner, health gates, PassengerTurret, and ImmuneToAbduction are parsed into the shared rules model. Live vehicle holds now absorb eligible units, preserve conventional damage on rejection, complete temporal abduction at erase time, emit the configured animation/events, and switch PassengerTurret by passenger count. Building/infantry passenger-hold edge cases, PSIONICSIMMUNE veteran ability parity, save/load, and multiplayer synchronization remain open.",
    },
    "new/newpoweredunitlogic.rst": {
        capabilityId: "ares.powered-by",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "missing", presentationStatus: "missing", saveLoadStatus: "missing", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true,
        tests: ["AresTechnoExtensions.test.ts", "AresPoweredUnitRuntimeDecision.test.ts", "AresPoweredByTrait.test.ts", "AresPoweredByObjectFactory.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "PoweredBy is parsed as a data-defined OR-list; ObjectFactory registration and generic provider matching plus powered-unit transitions are covered by a trait bridge. Power output accounting, superweapon availability coupling, save/load, and multiplayer synchronization remain open.",
    },
    "new/urbancombattrenches.rst": {
        capabilityId: "ares.urban-combat",
        parserStatus: "complete", normalizedModelStatus: "complete", runtimeStatus: "partial",
        aiStatus: "missing", presentationStatus: "missing", saveLoadStatus: "missing", multiplayerStatus: "partial",
        verificationStatus: "synthetic", deterministic: true,
        tests: ["AresUrbanCombat.test.ts", "AresUrbanCombatRuntimeAdapter.test.ts", "AresUrbanCombatProjectileHook.test.ts", "AresTechnoRulesIntegration.test.ts"],
        dependencies: ["ares.effective-ini"], targetModUsage: "required",
        notes: "Urban Combat fields are parsed and normalized; projectile occupant pass-through, fatal-rate, and damage decisions are integrated generically. Trench traversal, raidable capture, rubble transitions, foundation validation, broader projectile/occupant integration, save/load, and multiplayer synchronization remain open.",
    },
};

/**
 * Runtime slices that span multiple official documentation sections. These
 * entries are separate from the 131-leaf official document inventory so the
 * report can distinguish a complete availability service from the still
 * partial aggregate superweapon surface.
 */
export const ARES_IMPLEMENTATION_CAPABILITIES: readonly AresCapability[] = [
    {
        id: "ares.customizable-insignia",
        title: "Generic Ares customizable insignia",
        category: "new",
        sourceDocuments: ["new/customizableinsignia.rst"],
        documentedKeys: ["Insignia.Rookie", "Insignia.Veteran", "Insignia.Elite", "InsigniaFrame.Rookie", "InsigniaFrame.Veteran", "InsigniaFrame.Elite", "Insignia.ShowEnemy", "[General]EnemyInsignia"],
        documentedSections: ["TechnoType", "General"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresInsignia.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Rank-specific SHP/frame selection and enemy/observer visibility are wired through TechnoRules and PipOverlay. Render-host certification, missing-asset coverage, save/mod-hash, and multiplayer certification remain open.",
    },
    {
        id: "ares.customizable-veterancy",
        title: "MO-used customizable veterancy attribution",
        category: "new",
        sourceDocuments: ["new/customizableveterancy.rst"],
        documentedKeys: [
            "Trainable",
            "Experience.FromPassengers",
            "Experience.PromotePassengers",
            "Experience.PassengerModifier",
            "Experience.FromAirstrike",
            "Experience.AirstrikeModifier",
            "Experience.SpawnOwnerModifier",
            "Experience.SpawnModifier",
            "Experience.MindControlSelfModifier",
            "Experience.MindControlVictimModifier",
        ],
        documentedSections: ["TechnoType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "missing",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresCustomizableVeterancy.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Trainable and all documented Experience.* passenger, airstrike, spawn, and mind-control modifiers are normalized and routed through generic deterministic kill attribution. Complete occupier/passenger lifecycle behavior, presentation, AI, persistence, multiplayer, and target-content certification remain open.",
    },
    {
        id: "ares.bounty",
        title: "Generic Ares Bounty rewards",
        category: "new",
        sourceDocuments: ["new/bounty.rst"],
        documentedKeys: ["BountyEnablers", "Bounty", "Bounty.Display", "Bounty.Value", "Bounty.RookieValue", "Bounty.VeteranValue", "Bounty.EliteValue", "BountyDisplay", "GivesBounty"],
        documentedSections: ["General", "AudioVisual", "TechnoType", "Country"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresBounty.test.ts"],
        dependencies: ["ares.effective-ini", "ares.dynamic-sides-countries"],
        targetModUsage: "required",
        notes: "Bounty values, enablers, country gating, and weapon/crush destruction awards are wired through the generic Game.destroyObject path. Amount presentation, full-game persistence, multiplayer certification, and target-content verification remain open.",
    },
    {
        id: "ares.reverse-engineer",
        title: "Generic Ares reverse engineering",
        category: "new",
        sourceDocuments: ["new/reverseengineerlogic.rst"],
        documentedKeys: ["ReverseEngineersVictims", "CanBeReversed", "ReversedAs", "SpyEffect.Custom", "SpyEffect.UndoReverseEngineer"],
        documentedSections: ["BuildingType", "InfantryType", "VehicleType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "partial",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresReverseEngineer.test.ts", "AresFactoryOwnerPersistence.test.ts"],
        dependencies: ["ares.effective-ini", "ares.generic-prerequisites"],
        targetModUsage: "required",
        notes: "Grinder entry, ReversedAs output, production prerequisite exceptions, deterministic production-extension persistence, and spy reset are wired. EVA, AI, full-game save/load, lockstep, and target-content verification remain open.",
    },
    {
        id: "ares.custom-superweapons",
        title: "MO custom-superweapon host handlers",
        category: "new",
        sourceDocuments: ["new/superweapons.rst"],
        documentedKeys: ["Type=GenericWarhead", "Type=UnitDelivery", "Type=EMPulse", "Type=SonarPulse", "Type=DropPod", "Type=HunterSeeker", "Type=Battery", "Type=Firestorm", "Type=ChronoWarp", "SW.Animation", "SW.AnimationHeight", "SW.AnimationVisibility", "SW.Sound", "SW.ActivationSound", "EVA.*", "Message.*", "Text.*", "Light.*", "EMPulse.PulseBall", "DropPodWeapon", "DropPodTrailer"],
        documentedSections: ["SuperWeaponTypes"],
        parserStatus: "partial",
        normalizedModelStatus: "partial",
        runtimeStatus: "partial",
        aiStatus: "partial",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresMentalOmegaSuperWeaponHost.test.ts", "AresSuperWeaponAIHost.test.ts"],
        dependencies: ["ares.effective-ini", "ares.target-filters", "ares.superweapon-ai-targeting"],
        targetModUsage: "required",
        notes: "The local MO 3.3.6 scan shows 19 distinct superweapon Type values (UnitDelivery=39, GenericWarhead=23, EMPulse=13, HunterSeeker=9, DropPod=5, Battery=2, Firestorm=1, plus 11 vanilla types). All 19 are dispatched: GenericWarhead, UnitDelivery, SonarPulse, EMPulse, DropPod, HunterSeeker, and ChronoWarp effect classes, with Firestorm/Battery driven by the charge-drain lifecycle. Authored target-cell animation, activation/impact sound, EVA/Message labels, Text overlays, and Light fields use shared deferred presentation paths with explicit visibility/relation filtering. EMPulse PulseBall, DropPod infantry/trailer/impact behavior, Hunter Seeker lepton/profile behavior, and versioned per-instance/AttachEffect state codecs are covered by focused fixtures. Full AI breadth, in-flight/save restoration, target-content, and multiplayer certification remain open.",
    },
    {
        id: "ares.superweapon-ai-targeting",
        title: "MO custom-superweapon AI host coverage",
        category: "new",
        sourceDocuments: ["new/superweapons.rst"],
        documentedKeys: ["SW.AITargeting", "SW.AITargeting.Constraints", "SW.AITargeting.Preference", "SW.AIRequiresTarget", "SW.AIRequiresHouse", "SW.UseAITargeting", "SW.AllowAI", "EMPulse.TargetSelf", "EMPulse.Cannons", "DropPod.Types", "DropPodWeapon", "HunterSeeker.*"],
        documentedSections: ["SuperWeaponTypes"],
        parserStatus: "complete",
        normalizedModelStatus: "partial",
        runtimeStatus: "partial",
        aiStatus: "partial",
        presentationStatus: "missing",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresSuperWeaponAITargeting.test.ts", "AresSuperWeaponAIHost.test.ts"],
        dependencies: ["ares.effective-ini", "ares.target-filters"],
        targetModUsage: "required",
        notes: "The built-in AI host now routes SW.AutoFire, honors authored offensive/defensive preferred cells, ignores cloaked candidates for Nuke/LightningStorm/PsychicDominator/MultiMissile modes, filters candidate cells through the shared provider-range/designator/inhibitor gate, enforces inactive LightningStorm/Dominator constraints and AI-required house/land/water/content masks, scores MultiMissile by ThreatPosed, handles true no-target/LightningRandom modes, gates HunterSeeker on a target house, and covers EMPulse offensive/self targeting, UnitDelivery landing areas, and DropPod outer-sector targeting. Iron Curtain waits for team-script activation and ForceShield only responds through the defense path; manual UseAITargeting flow, complete custom-handler selector parity, presentation, persistence, and multiplayer certification remain open.",
    },
    {
        id: "ares.superweapon-post-dependent",
        title: "ChronoWarp/PostDependent two-stage host path",
        category: "new",
        sourceDocuments: ["new/superweapons.rst", "new/hardcodedunitproperties.rst"],
        documentedKeys: ["SW.PostDependent", "PreDependent", "PostClick", "Type=ChronoWarp", "SW.AffectsHouse", "SW.AffectsTarget", "SW.AllowAI"],
        documentedSections: ["SuperWeaponTypes"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresSuperWeaponPostDependent.test.ts", "AresChronoWarp.test.ts"],
        dependencies: ["ares.effective-ini", "ares.target-filters"],
        targetModUsage: "required",
        notes: "Case-insensitive dependent resolution and ChronoSphere fallback are covered; the first action records the source and the ChronoWarp dependent supplies the destination to the existing ChronoSphere effect. ChronoWarp itself is not treated as a direct teleport/damage handler. Full dependent graphs, cursor/presentation resources, AI, persistence, target-content, and multiplayer certification remain open.",
    },
    {
        id: "ares.chronoshift",
        title: "Ares Chronoshift eligibility and crush rules",
        category: "new",
        sourceDocuments: ["new/chronoshift.rst"],
        documentedKeys: ["Chronoshift.Allow", "Chronoshift.IsVehicle", "Chronoshift.Crushable", "ChronoInfantryCrush", "Chronosphere.ReconsiderBuildings", "Chronosphere.KillOrganic", "Chronosphere.KillTeleporters", "Chronosphere.AffectsIronCurtain", "Chronosphere.AffectsUnwarpable", "Chronosphere.AffectsUndeployable", "Chronosphere.BlowUnplaceable", "Chronosphere.KillCargo"],
        documentedSections: ["TechnoType", "BuildingType", "General"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresChronoshift.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "All documented Chronoshift fields are parsed and consumed by the shared Chronosphere path: eligibility, vehicle-building reclassification, crush rules, infantry-crush toggle, and the Kill/Affects/BlowUnplaceable controls. Warp-in/warp-out animations and EVA announcements cover presentation. Full transport side effects, save/load, and multiplayer/lockstep certification remain open.",
    },
    {
        id: "ares.pcx-cameos",
        title: "Generic Ares PCX cameo resolution",
        category: "new",
        sourceDocuments: ["new/pcxcameos.rst"],
        documentedKeys: ["CameoPCX", "AltCameoPCX", "SidebarPCX"],
        documentedSections: ["TechnoType", "SuperWeapon"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresPcxCameos.test.ts", "AresSuperWeapons.test.ts", "AresCompatibilityScanner.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "CameoPCX, AltCameoPCX, and SidebarPCX are normalized with .pcx validation, 60x48 validation during GameLoader VFS discovery, and legacy fallback precedence. The validated manifest reaches the HUD, which decodes direct PCX surfaces and selects them per sidebar item with a legacy SHP fallback. PCX cameos are presentation-only and intentionally excluded from the simulation content hash (which covers effective INIs). Multiplayer certification remains open.",
    },
    {
        id: "ares.damage-particle-systems",
        title: "Generic Ares damage particle-system selection",
        category: "new",
        sourceDocuments: ["new/damageparticlesystems.rst"],
        documentedKeys: ["[TechnoType]DamageSparks", "[TechnoType]DamageSmokeParticleSystems", "[TechnoType]DamageSparksParticleSystems", "DamageParticleSystems"],
        documentedSections: ["TechnoType", "ParticleSystem"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresParticleSystems.test.ts", "AresDamageParticles.test.ts", "AresDamageParticlesTechnoIntegration.test.ts", "AresDamageParticlesRenderIntegration.test.ts", "AresCompatibilityScanner.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "ParticleSystem and Particle definitions are parsed into a shared case-insensitive registry; DamageSparks and explicit Smoke/Spark lists retain Ares precedence and BehavesLike filtering. Authored smoke images render through the parsed ParticleSystem -> Particle -> Image chain for every techno type, with the retail yellow threshold and a bounded particle cap. Authored spark systems repeat through the shared movement-particle effect with authored colors, velocity, spawn radius, and cap, including the Cyborg default. Non-Smoke/Spark BehavesLike is a documented Ares 0.7 limitation (the docs say only Smoke and Spark are fully supported). Save/load and multiplayer certification remain open.",
    },
    {
        id: "ares.weapon-visuals",
        title: "Generic Ares weapon visual extensions",
        category: "new",
        sourceDocuments: ["new/weapons.rst"],
        documentedKeys: ["[WeaponTypes]", "Beam.Color", "Beam.IsHouseColor", "Beam.Duration", "Beam.Amplitude", "Bolt.Color1", "Bolt.Color2", "Bolt.Color3", "Wave.IsLaser", "Wave.IsBigLaser", "Wave.Color", "Wave.IsHouseColor", "Wave.ReverseAgainstVehicles", "Wave.ReverseAgainstAircraft", "Wave.ReverseAgainstBuildings", "Wave.ReverseAgainstInfantry", "Wave.ReverseAgainstOthers"],
        documentedSections: ["WeaponTypes", "Weapon"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresWeaponVisuals.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Weapon visual fields are parsed with Ares defaults and wired into the shared render/simulation layers: Beam color/house color/duration/amplitude, all three electric-bolt colors, enabled laser/sonic wave meshes with custom/house colors, Wave.ReverseAgainst* direction selection, and non-Sonic wave AmbientDamage pass-through. Native wave lifecycle, save/load, and multiplayer certification remain open.",
    },
    {
        id: "ares.custom-ivan-bombs",
        title: "Generic Ares customizable Ivan Bombs",
        category: "new",
        sourceDocuments: ["new/weapons.rst"],
        documentedKeys: ["IvanBomb.Warhead", "IvanBomb.Damage", "IvanBomb.Detachable", "IvanBomb.DestroysBridges", "IvanBomb.Delay", "IvanBomb.AttachSound", "IvanBomb.TickingSound", "IvanBomb.Image", "IvanBomb.FlickerRate", "IvanBomb.CanDetonateTimeBomb", "IvanBomb.CanDetonateDeathBomb", "IvanBomb.DetonateOnSell"],
        documentedSections: ["Weapon", "Warhead", "CombatDamage"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresIvanBombs.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Weapon-local bomb damage, warhead, delay, bridge, detachable, sell, image, flicker, and sound settings are normalized and flow through the shared Ivan charge, targeting, bridge, sell, and render paths. Remote-detonation UI, death-bomb lifecycle parity, persistence, and multiplayer certification remain open.",
    },
    {
        id: "ares.superweapon-availability",
        title: "Generic Ares superweapon availability and grant/revoke",
        category: "new",
        sourceDocuments: ["new/superweapons.rst"],
        documentedKeys: [
            "SW.RequiredHouses", "SW.ForbiddenHouses", "SW.AuxBuildings", "SW.NegBuildings",
            "SW.AllowPlayer", "SW.AllowAI", "SW.Shots", "SW.AlwaysGranted",
            "SW.ShowCameo", "SW.TimerVisibility", "SW.Group",
        ],
        documentedSections: ["SuperWeapon"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "complete",
        aiStatus: "partial",
        presentationStatus: "partial",
        saveLoadStatus: "partial",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresSuperWeaponAvailability.test.ts", "AresSuperWeapons.test.ts", "AresSuperWeaponPresentationAdapter.test.ts", "AresCompatibilityScanner.test.ts"],
        dependencies: ["ares.effective-ini", "ares.target-filters"],
        targetModUsage: "required",
        notes: "Parser/evaluator, generic owner adapter, provider-based grant/revoke, AlwaysGranted, finite Shots, activation-time shot gating, shared SW.ShowCameo sidebar filtering, and relation-aware SW.TimerVisibility timer filtering are implemented. SW.Group is retained as normalized data for AI/action consumers; broader AI certification, persistence, and multiplayer/network certification remain partial.",
    },
    {
        id: "ares.emp",
        title: "Ares EMP duration/cap counters, immunity, and Techno paralysis state",
        category: "restored",
        sourceDocuments: ["restored/emp.rst"],
        documentedKeys: ["EMP.Duration", "EMP.Cap", "ImmuneToEMP", "EMP.Modifier", "AffectsEnemies"],
        documentedSections: ["Warhead", "TechnoType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "partial",
        presentationStatus: "partial",
        saveLoadStatus: "partial",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresEMP.test.ts", "AresEMPulse.test.ts", "WarheadAresEffectIntegration.test.ts"],
        dependencies: ["ares.effective-ini", "ares.warhead-effects"],
        targetModUsage: "required",
        notes: "Per-Techno EMP counters, cap/immunity/modifier, movement/attack paralysis, power-output blackout, factory/production suspension, spawner/slave suspension, powered-superweapon pause, and aircraft crash entry are wired through EmpTrait and Warhead.applyEmp. Sparkle presentation, mission restoration, and full subsystem notifications remain open.",
    },
    {
        id: "ares.attach-effects",
        title: "Generic AttachEffect status effects",
        category: "new",
        sourceDocuments: ["new/status-effects.rst"],
        documentedKeys: ["AttachEffect.*"],
        documentedSections: ["TechnoType", "Warhead"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "partial",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresAttachEffect.test.ts", "AresAttachEffectCombat.test.ts", "AresAttachEffectRuntime.test.ts", "AresAttachEffectTraitBridge.test.ts", "AresAttachEffectPresentation.test.ts", "WarheadAttachEffectIntegration.test.ts"],
        dependencies: ["ares.effective-ini", "ares.warhead-effects"],
        targetModUsage: "required",
        notes: "TechnoType/Warhead AttachEffect fields are normalized; ObjectFactory registration and a generic per-tick trait cover spawn timing, renewal, protection retry, effect instances, and reapplication/stacking decisions with deterministic cleanup. All documented fields are consumed: Duration, Animation, TemporalHidesAnim, Speed/Armor/Firepower/ROF multipliers, Cloakable, ForceDecloak, DiscardOnEntry, PenetratesIronCurtain, Delay/InitialDelay, Cumulative, AnimResetOnReapply. Temporary Cloakable sources are applied and removed through the shared CloakableTrait without disturbing permanent/veteran sources. Attached and standalone animation damage now use the shared frame clock and Warhead/Weapon delivery path. AI, transport/temporal replay, persistence, and network certification remain open.",
    },
    {
        id: "ares.urban-combat",
        title: "Ares Urban Combat trenches and raidable bunkers",
        category: "new",
        sourceDocuments: ["new/urbancombattrenches.rst"],
        documentedKeys: ["UC.PassThrough", "UC.FatalRate", "UC.DamageMultiplier", "SubjectToTrenches", "Bunker.Raidable", "Rubble.Destroyed", "Rubble.Intact", "IsTrench", "CanBeOccupiedBy"],
        documentedSections: ["BuildingType", "Projectile", "InfantryType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "missing",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresUrbanCombat.test.ts", "AresUrbanCombatProjectileHook.test.ts", "AresUrbanCombatRuntimeAdapter.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Urban Combat fields are normalized; the projectile path applies generic pass-through, fatal-rate, and occupant damage decisions while preserving ordinary detonation when optional data is absent. Trench traversal, raidable capture, rubble transitions, AI, presentation, and persistence remain open.",
    },
    {
        id: "ares.chrono-prisons",
        title: "Ares Chrono Prisons and abductor logic",
        category: "new",
        sourceDocuments: ["new/chronoprisons.rst"],
        documentedKeys: ["Abductor", "Abductor.Temporal", "Abductor.ChangeOwner", "PassengerTurret", "ImmuneToAbduction"],
        documentedSections: ["Weapon", "TechnoType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresChronoPrisons.test.ts", "AresChronoPrisonBridge.test.ts", "AresChronoPrisonIntegration.test.ts", "AresChronoPrisonRuntimeDecision.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Abductor, Abductor.Temporal, Abductor.ChangeOwner, health gates, PassengerTurret, and ImmuneToAbduction are parsed into the shared rules model. Live vehicle holds absorb eligible units through the warhead path, preserve conventional damage on rejection, and expose passenger-turret behavior. AI, persistence, and full network certification remain open.",
    },
    {
        id: "ares.firestorm-wall",
        title: "Ares Firestorm wall linking, contact effects, and projectile interception",
        category: "restored",
        sourceDocuments: ["restored/firestormwall.rst"],
        documentedKeys: ["Firestorm.Wall", "SubjectToFirestorm", "IgnoresFirestorm", "FirestormActiveAnim", "FirestormIdleAnim"],
        documentedSections: ["BuildingType", "Projectile"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "partial",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresFirestorm.test.ts", "AresFirestormWallPresentation.test.ts", "AresFirestormWallFlicker.test.ts"],
        dependencies: ["ares.effective-ini", "ares.superweapon-charge-drain"],
        targetModUsage: "required",
        notes: "Same-owner four-way wall linking, per-owner activation via charge-drain, full projectile-path interception, direct-contact immolation, and damage-to-active-charge feedback are wired through normal building/collision/warhead services. FirestormActiveAnim/FirestormIdleAnim now match the Ares docs: random flicker on wall sections using the deterministic game RNG, dispatched as transient TriggerAnimEvents (idle anim while inactive, active anim while draining). Persistent/trigger/network state and AI remain open.",
    },
    {
        id: "ares.killing-drivers",
        title: "Ares KillDriver, ProtectedDriver, and CanDrive semantics",
        category: "new",
        sourceDocuments: ["new/killingdrivers.rst"],
        documentedKeys: ["KillDriver", "KillDriver.KillBelowPercent", "KillDriver.Chance", "KillDriver.Owner", "KillDriver.RemoveVeterancy", "ProtectedDriver", "CanDrive"],
        documentedSections: ["Warhead", "TechnoType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "partial",
        presentationStatus: "partial",
        saveLoadStatus: "partial",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresKillingDrivers.test.ts"],
        dependencies: ["ares.effective-ini", "ares.operator"],
        targetModUsage: "required",
        notes: "KillDriver and ProtectedDriver use a normalized driver state with deterministic owner resolution, passenger/operator handling, and driverless movement/weapon suppression. All documented fields are covered: KillDriver.Owner/KillBelowPercent/Chance/RemoveVeterancy, ProtectedDriver.MinHealth, CanDrive, CanBeDriven, and Country.CanBeDriven. The docs specify no audio fields; the remaining gap is target-content verification.",
    },
    {
        id: "ares.vehicle-thief",
        title: "Ares VehicleThief hijack and driverless-vehicle reclaim",
        category: "restored",
        sourceDocuments: ["restored/vehicle-thief.rst"],
        documentedKeys: ["VehicleThief", "VehicleThief.EnterSound", "VehicleThief.LeaveSound", "VehicleThief.KillPilots", "VehicleThief.BreakMindControl", "VehicleThief.Allowed", "VehicleThief.OneTime"],
        documentedSections: ["InfantryType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "partial",
        presentationStatus: "partial",
        saveLoadStatus: "partial",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresVehicleThief.test.ts", "MindControlVehicleThiefLifecycle.test.ts"],
        dependencies: ["ares.effective-ini", "ares.killing-drivers", "ares.operator"],
        targetModUsage: "required",
        notes: "VehicleThief and CanDrive share a data-defined hijack action path with enemy hijack, neutral driverless reclaim, operator passengers, absorbed-hijacker recovery, and target/task integration. All documented fields are covered: VehicleThief.Allowed, EnterSound/LeaveSound, BreakMindControl, OneTime, KillPilots, mind-control link transfer, and grinder reimbursement. The remaining gap is target-content verification.",
    },
    {
        id: "ares.operator",
        title: "Ares data-defined infantry operators",
        category: "new",
        sourceDocuments: ["new/operator.rst"],
        documentedKeys: ["Operator", "Operator.Anim"],
        documentedSections: ["TechnoType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "partial",
        presentationStatus: "partial",
        saveLoadStatus: "complete",
        multiplayerStatus: "complete",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresOperator.test.ts", "AresOperatorCloak.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Specific InfantryType operators and the _ANY_ sentinel are evaluated from transport/garrison passengers; missing operators disable only movement and weapons while preserving building services. Unoperated units/structures no longer cloak themselves (matching the Ares docs), while Cloak Generators still can. AI and presentation integration remain open.",
    },
    {
        id: "ares.powered-by",
        title: "Ares PoweredBy powered-unit logic",
        category: "new",
        sourceDocuments: ["new/newpoweredunitlogic.rst"],
        documentedKeys: ["PoweredBy"],
        documentedSections: ["UnitType", "BuildingType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresPoweredByObjectFactory.test.ts", "AresPoweredByTrait.test.ts", "AresPoweredUnitRuntimeDecision.test.ts", "AresPoweredByPresentation.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "PoweredBy alternatives are normalized as an ordered data-defined OR-list; ObjectFactory registration and generic provider matching plus powered-unit power-down/power-up decisions are covered by a trait bridge. Unpowered units now render at half brightness (vehicle/aircraft/infantry renderables) using the shared offline-light path, matching the shut-down robot-tank presentation. Power output accounting, superweapon availability, AI, and persistence remain open.",
    },
    {
        id: "ares.superweapon-providers",
        title: "Ares superweapon provider buildings",
        category: "new",
        sourceDocuments: ["new/superweapons.rst"],
        documentedKeys: ["SW.AuxBuildings", "SW.NegBuildings", "EMPulseCannon", "HSBuilding"],
        documentedSections: ["SuperWeapon", "BuildingType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "partial",
        presentationStatus: "partial",
        saveLoadStatus: "partial",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresSuperWeaponProviders.test.ts", "AresSuperWeaponAvailability.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Provider-based superweapon grant/revoke, EMPulse launch-site selection, and Hunter Seeker launch building selection are wired through the shared availability and targeting paths. Full AI depth, persistence, and network certification remain open.",
    },
    {
        id: "ares.superweapon-presentation",
        title: "Ares superweapon presentation events",
        category: "new",
        sourceDocuments: ["new/superweapons.rst"],
        documentedKeys: ["SW.Animation", "SW.AnimationVisibility", "SW.Sound", "SW.ActivationSound", "EVA.*", "Message.*", "Text.*", "Light.*"],
        documentedSections: ["SuperWeapon"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresSuperWeaponPresentationAdapter.test.ts", "AresSuperWeaponPresentationRuntime.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "Authored SW.Animation, SW.AnimationVisibility, SW.Sound, SW.ActivationSound, EVA.*, Message.*, Text.*, and Light.* flow through shared deferred render/audio/UI/lighting events from the common activation path. Full animation/sound asset parity, AI, persistence, and network certification remain open.",
    },
    {
        id: "ares.ifv-modes",
        title: "Ares multiple IFV modes, turret indices, and repair voice fields",
        category: "new",
        sourceDocuments: ["new/miscellaneousmoddingenhancements.rst"],
        documentedKeys: ["IFVMode", "WeaponTurretIndex1", "WeaponTurretIndex2", "WeaponTurretIndex3", "WeaponUIName1", "WeaponUIName2", "WeaponUIName3", "VoiceIFVRepair"],
        documentedSections: ["InfantryType", "VehicleType"],
        parserStatus: "complete",
        normalizedModelStatus: "complete",
        runtimeStatus: "partial",
        aiStatus: "missing",
        presentationStatus: "partial",
        saveLoadStatus: "missing",
        multiplayerStatus: "partial",
        deterministic: true,
        verificationStatus: "synthetic",
        tests: ["AresTechnoExtensions.test.ts", "AresIfvRuntimeIntegration.test.ts", "AresVoiceIfvRepair.test.ts"],
        dependencies: ["ares.effective-ini"],
        targetModUsage: "required",
        notes: "IFVMode, 1-based WeaponTurretIndex*, WeaponUIName*, and VoiceIFVRepair are normalized generically; passenger changes re-evaluate the selected weapon, turret, and tooltip through the shared GunnerTrait path. VoiceIFVRepair is now consumed by the repair-order feedback path (falls back to VoiceAttack when absent). Full passenger weapon/turret parity, save/load, and multiplayer synchronization remain open.",
    },
];

function capabilityIdFor(path: string): string {
    return `ares.docs.${path.replace(/\.rst$/i, "").replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-|-$/g, "")}`;
}

function defaultCapability(path: string): AresCapability {
    const override = OVERRIDES[path] ?? {};
    const category = categoryFor(path);
    return {
        id: override.capabilityId ?? capabilityIdFor(path),
        title: titleFor(path),
        category,
        sourceDocuments: [path],
        documentedKeys: DOCUMENTED_KEYS[path] ?? [],
        documentedSections: [],
        parserStatus: override.parserStatus ?? "missing",
        normalizedModelStatus: override.normalizedModelStatus ?? "missing",
        runtimeStatus: override.runtimeStatus ?? "missing",
        aiStatus: override.aiStatus ?? "missing",
        presentationStatus: override.presentationStatus ?? "missing",
        saveLoadStatus: override.saveLoadStatus ?? "missing",
        multiplayerStatus: override.multiplayerStatus ?? "missing",
        deterministic: override.deterministic ?? false,
        verificationStatus: override.verificationStatus ?? "unverified",
        tests: override.tests ?? [],
        dependencies: override.dependencies ?? ["ares.effective-ini"],
        targetModUsage: override.targetModUsage ?? "unknown",
        notes: override.notes,
    };
}

/** Every non-index leaf in the official Ares documentation tree. */
export const ARES_FEATURE_CATALOG: readonly AresCapability[] = DOCUMENTATION_PATHS.map(defaultCapability);

export const ARES_DOCUMENTATION_DOCUMENTS: readonly AresDocumentationDocument[] = ARES_FEATURE_CATALOG.map((feature) => ({
    path: feature.sourceDocuments[0],
    category: feature.category,
    capabilityId: feature.id,
}));

export function getAresCapability(id: string): AresCapability | undefined {
    return ARES_FEATURE_CATALOG.find((feature) => feature.id === id);
}

export function getAresImplementationCapability(id: string): AresCapability | undefined {
    return ARES_IMPLEMENTATION_CAPABILITIES.find((feature) => feature.id === id);
}

export function getAresCatalogSummary(): {
    documents: number;
    capabilities: number;
    categories: Record<AresDocumentationCategory, number>;
    completeRuntime: number;
    partialRuntime: number;
    missingRuntime: number;
} {
    const categories: Record<AresDocumentationCategory, number> = { new: 0, restored: 0, bugfix: 0, ui: 0 };
    for (const feature of ARES_FEATURE_CATALOG) categories[feature.category]++;
    return {
        documents: ARES_DOCUMENTATION_DOCUMENTS.length,
        capabilities: ARES_FEATURE_CATALOG.length,
        categories,
        completeRuntime: ARES_FEATURE_CATALOG.filter((feature) => feature.runtimeStatus === "complete").length,
        partialRuntime: ARES_FEATURE_CATALOG.filter((feature) => feature.runtimeStatus === "partial").length,
        missingRuntime: ARES_FEATURE_CATALOG.filter((feature) => feature.runtimeStatus === "missing").length,
    };
}
