export interface ExtensionFeature {
    id: string;
    description: string;
    implemented: boolean;
    parserImplemented: boolean;
    runtimeImplemented: boolean;
    tests: string[];
    notes?: string;
}

/**
 * A deliberately small, explicit starting registry.  A feature is not marked
 * implemented merely because the scanner recognizes its spelling; runtime
 * support must be added and verified independently.
 */
export const DEFAULT_ARES_FEATURES: readonly ExtensionFeature[] = [
    {
        id: "ares.additional-armor-types",
        description: "Additional ArmorTypes and per-armor Versus values",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresCompatibilityScanner.test.ts", "AresArmor.test.ts"],
        notes: "Additional armor IDs, dynamic Versus values, and separate force-fire/retaliation/passive-acquire target gates are wired into weapon selection.",
    },
    {
        id: "ares.chronoshift",
        description: "Ares Chronoshift eligibility, Chronosphere controls, and building placement rules",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresChronoshift.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "Chronoshift.Allow, Chronoshift.IsVehicle, Chronoshift.Crushable, ChronoInfantryCrush, and the documented Chronosphere Kill/Affects/BlowUnplaceable controls are parsed and consumed by the shared Chronosphere path. Vehicle-type and explicitly undeployable buildings use foundation-aware relocation, cargo can be killed deterministically, and non-crushable/infantry-crush collisions follow the authored rules. Full transport side effects, save/load, and multiplayer/lockstep certification remain open.",
    },
    {
        id: "ares.chrono-prisons",
        description: "Ares Chrono Prison abduction and passenger-turret rules",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresChronoPrisons.test.ts", "AresChronoPrisonRuntimeDecision.test.ts", "AresChronoPrisonBridge.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "The documented Abductor, Abductor.Temporal, Abductor.ChangeOwner, health gates, PassengerTurret, and ImmuneToAbduction fields are parsed into the shared rules model. Live vehicle holds now absorb eligible units, preserve conventional damage on rejection, complete temporal abduction at erase time, emit the configured animation/events, and switch PassengerTurret by passenger count. Building/infantry passenger-hold edge cases, PSIONICSIMMUNE veteran ability parity, save/load, and multiplayer synchronization remain open.",
    },
    {
        id: "ares.customizable-insignia",
        description: "Custom veterancy insignia and enemy insignia visibility",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresInsignia.test.ts"],
        notes: "Insignia and InsigniaFrame values are parsed and consumed by the generic PipOverlay SHP/frame path. Missing-file fallback and the vanilla path remain intact; render-host, save/mod-hash, and multiplayer certification remain open.",
    },
    {
        id: "ares.customizable-veterancy",
        description: "Ares Trainable and customizable veterancy behavior",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresCustomizableVeterancy.test.ts"],
        notes: "Trainable and all documented Experience.* passenger, airstrike, spawn, and mind-control modifiers are normalized and routed through generic deterministic kill-credit attribution. Airstrike designator, passenger gating/promotion, spawned-owner, mind-controller, and Trainable=no decisions are covered; full occupier/passenger lifecycle, presentation, persistence, AI, and multiplayer certification remain open.",
    },
    {
        id: "ares.bounty",
        description: "Ares bounty rewards, values, and display rules",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresBounty.test.ts"],
        notes: "Bounty, Bounty.Display, value tiers, BountyEnablers, BountyDisplay, and GivesBounty are normalized; weapon/crush destruction awards use the generic Game.destroyObject path and publish a shared signed world-text event when display is enabled. Save/load and multiplayer certification remain open.",
    },
    {
        id: "ares.damage-particle-systems",
        description: "Ares damage sparks and custom damage particle-system selection",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresParticleSystems.test.ts", "AresDamageParticles.test.ts", "AresDamageParticlesTechnoIntegration.test.ts", "AresDamageParticlesRenderIntegration.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "ParticleSystem and Particle definitions are parsed into a shared case-insensitive registry; DamageSparks and explicit Smoke/Spark lists retain Ares precedence and BehavesLike filtering. Authored smoke images now render through the parsed ParticleSystem -> Particle -> Image chain for every techno type, with the retail yellow threshold and a bounded particle cap. Authored spark systems now repeat through the shared movement-particle effect with authored colors, velocity, spawn radius, and cap, including the Cyborg default. Full non-smoke particle BehavesLike parity, save/load, and multiplayer certification remain open.",
    },
    {
        id: "ares.weapon-visuals",
        description: "Ares weapon beam, electric-bolt, and wave visual extensions",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresWeaponVisuals.test.ts"],
        notes: "Beam.Color/IsHouseColor/Duration/Amplitude, Bolt.Color1/2/3, Wave.IsLaser/IsBigLaser/Color/IsHouseColor/ReverseAgainst*, and standalone [WeaponTypes] declarations are parsed and consumed by the shared renderer/simulation path. Native wave lifecycle, persistence, and multiplayer certification remain open.",
    },
    {
        id: "ares.custom-ivan-bombs",
        description: "Ares weapon-local customizable Ivan Bombs",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresIvanBombs.test.ts"],
        notes: "Weapon-local IvanBomb damage, warhead, delay, bridge, detachable, sell, image, flicker, and sound settings are parsed and consumed by the shared charge/targeting/presentation path. Remote-detonation UI, death-bomb lifecycle parity, persistence, and multiplayer certification remain open.",
    },
    {
        id: "ares.urban-combat",
        description: "Ares Urban Combat, trench, and advanced rubble rules",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresUrbanCombat.test.ts", "AresUrbanCombatRuntimeAdapter.test.ts", "AresUrbanCombatProjectileHook.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "The documented Urban Combat fields are normalized and the projectile path now applies generic pass-through, fatal-rate, and occupant damage decisions while preserving ordinary detonation when optional data is absent. Trench traversal, raidable capture, rubble transitions, foundation validation, broader projectile/occupant integration, save/load, and multiplayer synchronization remain open.",
    },
    {
        id: "ares.pcx-cameos",
        description: "PCX cameo files for TechnoTypes and superweapons",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresPcxCameos.test.ts", "AresSuperWeapons.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "CameoPCX, AltCameoPCX, and SidebarPCX are normalized with .pcx validation, 60x48 validation during VFS discovery, and legacy fallback precedence. GameLoader carries the validated manifest to the HUD, which decodes direct PCX surfaces and selects them per sidebar item with a legacy SHP fallback; save/mod-hash coverage and multiplayer certification remain open.",
    },
    {
        id: "ares.reverse-engineer",
        description: "Ares reverse-engineering eligibility and output rules",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresReverseEngineer.test.ts", "AresFactoryOwnerPersistence.test.ts"],
        notes: "ReverseEngineersVictims, CanBeReversed, ReversedAs, and spy reset are normalized and consumed by the grinder/production path. EVA, AI, full-game save/load, and lockstep certification remain open.",
    },
    {
        id: "ares.ifv-modes",
        description: "Ares multiple IFV modes, turret indices, and repair voice fields",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresTechnoExtensions.test.ts", "AresIfvRuntimeIntegration.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "IFVMode, 1-based WeaponTurretIndexX, WeaponUINameX, and VoiceIFVRepair are normalized generically; passenger changes now re-evaluate the selected weapon, turret, and tooltip through the shared IFV path. Repair-voice consumption, full passenger weapon/turret parity, save/load, and multiplayer synchronization remain open.",
    },
    {
        id: "ares.powered-by",
        description: "Ares data-defined PoweredBy provider relationships",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresTechnoExtensions.test.ts", "AresPoweredUnitRuntimeDecision.test.ts", "AresPoweredByTrait.test.ts", "AresPoweredByObjectFactory.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "PoweredBy alternatives are normalized as an ordered data-defined OR-list; ObjectFactory registration and generic provider matching plus powered-unit power-down/power-up decisions are covered by a trait bridge. Power output accounting, superweapon availability coupling, save/load, and multiplayer synchronization remain open.",
    },
    {
        id: "ares.custom-sides",
        description: "Data-defined sides beyond the vanilla side set",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSides.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "Dynamic side IDs, authored ordering, registry lookup, stable player identity, lobby ownership, and data-defined score presentation are verified; remaining legacy HUD adapters are tracked separately.",
    },
    {
        id: "ares.custom-countries",
        description: "Data-defined countries and side presentation",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSides.test.ts", "CountryIcon.test.ts"],
        notes: "Country IDs, side IDs, lobby ordering, multiplayer filtering, provenance, stable player identity, and explicit presentation resources are data-driven; legacy adapters remain for older simulation paths.",
    },
    {
        id: "ares.side-ui",
        description: "Ares side-specific sidebar, EVA, loading, result-banner, and multiplayer score presentation",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSides.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "Sidebar MIX/Yuri filename selection, tooltip color, EVA tag, side/country loading themes, GraphicalText result banners, multiplayer score background/palette/bar assets, and win/lose themes use the generic side presentation path. Missing assets retain the vanilla fallback; save/mod-hash and live network certification remain open.",
    },
    {
        id: "ares.generic-prerequisites",
        description: "Generic and composable prerequisite expressions",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresPrerequisites.test.ts"],
        notes: "Supports generic groups, alternate TechnoTypes, negative prerequisites, alternative lists, required theaters when map context is available, and stolen-tech gates.",
    },
    {
        id: "ares.factory-owner-prerequisites",
        description: "FactoryOwners and FactoryOwners.Forbidden production restrictions",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresPrerequisites.test.ts", "AresFactoryOwnerPersistence.test.ts"],
        notes: "Initial-factory-country checks, active HasAllPlans buildings, and Permanent capture plans are wired. Production extension state now has a versioned serializer/restorer; full-game snapshot integration remains open because current saves resume action logs.",
    },
    {
        id: "ares.custom-foundations",
        description: "Non-rectangular building foundation cells",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresCompatibilityScanner.test.ts", "AresFoundation.test.ts"],
        notes: "Foundation=Custom cells are parsed with their optional outline and used by placement preview, build validation, and tile occupation; factory-specific exit behavior remains a separate compatibility task.",
    },
    {
        id: "ares.operator",
        description: "Data-defined infantry operators for vehicles and buildings",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresOperator.test.ts"],
        notes: "Specific InfantryType operators and _ANY_ are normalized and evaluated from transport/garrison passengers; missing operators disable only movement and weapons while preserving building services. Save/load is derived from passenger state; AI and presentation integration remain open.",
    },
    {
        id: "ares.killing-drivers",
        description: "KillDriver, ProtectedDriver, and CanDrive vehicle-driver semantics",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresKillingDrivers.test.ts"],
        notes: "KillDriver and ProtectedDriver use a normalized driver state, deterministic owner resolution, passenger/operator handling, driverless movement/weapon suppression, and optional veterancy reset on ownership transfer. CanDrive and TechnoType/Country CanBeDriven gates feed the generic VehicleThief reclaim path; broader Ares trigger/script, AI, presentation, save, and network parity remain open.",
    },
    {
        id: "ares.vehicle-thief",
        description: "VehicleThief/CanDrive hijack and driverless-vehicle reclaim actions",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresVehicleThief.test.ts"],
        notes: "VehicleThief and CanDrive share a data-defined hijack action path. Enemy hijacks, neutral DriverKilled reclaim, TechnoType/Country CanBeDriven gates, mind-control cleanup, absorbed-hijacker recovery/recycle state, and target/task integration are wired; building hijacks, survivor pilot-count integration, sounds, and trigger/event parity remain open.",
    },
    {
        id: "ares.emp",
        description: "Ares EMP duration/cap counters, immunity, and Techno paralysis state",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresEMP.test.ts"],
        notes: "EMP.Duration/Cap, EMP.Modifier, default immunity including SuperWeapon2 providers, same-owner EMP-capable-weapon TypeImmune, ImmuneToEMP, AffectsEnemies, veteran EMPIMMUNE, per-Techno counters, movement/attack paralysis, unloading-boundary deferral, power-output blackout, factory/production suspension, spawner/slave suspension, powered-superweapon pause, and flying-aircraft crash entry are wired; sparkle presentation and full subsystem notifications remain separate.",
    },
    {
        id: "ares.emp-threshold",
        description: "EMP.Threshold parsing and destruction thresholds for airborne Technos",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresEMP.test.ts"],
        notes: "Positive thresholds and negative in-air thresholds are evaluated after EMP counter updates; parachuting and non-air targets follow the documented distinction. Full hover/aircraft edge coverage, persistence, and network certification remain separate.",
    },
    {
        id: "ares.custom-superweapons",
        description: "Data-defined superweapon handlers and target filters",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeapons.test.ts", "AresCompatibilityScanner.test.ts", "GenericWarheadEffect.test.ts", "AresBattery.test.ts", "AresChronoWarp.test.ts", "AresMentalOmegaSuperWeaponHost.test.ts", "AresSuperWeaponAIHost.test.ts", "AresSuperWeaponPresentationRuntime.test.ts"],
        notes: "Generic host paths cover GenericWarhead, UnitDelivery, EMPulse, SonarPulse, DropPod, HunterSeeker, Battery, Firestorm, and the ChronoWarp destination stage with representative Mental Omega fixtures. Authored SW.Animation, SW.AnimationVisibility, SW.Sound, SW.ActivationSound, EVA.*, Message.*, Text.*, and Light.* now flow through shared deferred render/audio/UI events. EMPulse PulseBall placement, DropPod infantry/trailer/impact presentation, native-lepton Hunter Seeker proximity, and shared Hunter Seeker flight profiles are wired; versioned per-instance and AttachEffect state codecs are available. The aggregate 96-definition custom-type surface remains partial; unsupported handlers, full AI breadth, complete in-flight/save restoration, target-content, and multiplayer certification remain open.",
    },
    {
        id: "ares.target-filters",
        description: "Common Ares house and target eligibility filters",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponFilters.test.ts"],
        notes: "AffectsHouse/AffectsTarget masks and house relations are normalized for the generic superweapon target layer; empty-cell and handler-specific behavior remains separate.",
    },
    {
        id: "ares.superweapon-availability",
        description: "Common Ares superweapon availability and grant-state fields",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponAvailability.test.ts", "AresSuperWeapons.test.ts", "AresSuperWeaponPresentationAdapter.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "The generic parser/evaluator, owner adapter, provider-based grant/revoke lifecycle, AlwaysGranted handling, finite Shots tracking, activation-time shot gate, SW.ShowCameo sidebar filtering, and SW.TimerVisibility relation filtering are implemented. SW.Group remains normalized for AI/action consumers; full AI certification, charge-lifecycle edge coverage, persistence, and multiplayer/network certification remain partial.",
    },
    {
        id: "ares.superweapon-target-requirements",
        description: "Manual Ares superweapon SW.RequiresTarget and SW.RequiresHouse gates",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponTargeting.test.ts"],
        notes: "Manual cell/content and house-relation validation follows Antares IsCellEligible/IsTechnoEligible semantics; AI target selection and cursor presentation remain separate.",
    },
    {
        id: "ares.superweapon-shroud-targeting",
        description: "Ares SW.FireIntoShroud visibility gate for superweapon activation",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponTargeting.test.ts", "AresSuperWeapons.test.ts"],
        notes: "The documented default is permissive; when explicitly disabled, manual activation rejects only unexplored cells using the owner's MapShroud, while temporary reveals remain valid. AI actions pass through the same final activation gate.",
    },
    {
        id: "ares.superweapon-fire-mode",
        description: "Ares SW.AutoFire and SW.ManualFire activation policy",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponTargeting.test.ts", "AresSuperWeapons.test.ts"],
        notes: "Auto-only superweapons reject human click actions while allowing AI-created actions; ManualFire remains ignored when AutoFire is disabled, matching Antares. Human automatic target selection is a separate host/AI integration task.",
    },
    {
        id: "ares.superweapon-charge-drain",
        description: "Ares charge-drain timers, ratio conversion, and Money.Drain* scheduling",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponChargeDrain.test.ts"],
        notes: "The shared timer implements Antares' Ready/Draining/Charging conversion, per-SW/global charge-to-drain ratio, scheduled money transactions, insufficient-funds stop, and Unstoppable-aware deactivation API. Firewall wall behavior, active-effect teardown, and full UI/action serialization remain separate.",
    },
    {
        id: "ares.superweapon-charge-state",
        description: "Ares SW.InitialReady and SW.VirtualCharge timer semantics",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponCharge.test.ts"],
        notes: "Initial grants and deterministic elapsed charging while a VirtualCharge superweapon is unavailable are wired; per-house shot-history re-grant semantics and save/load of unavailable intervals remain open.",
    },
    {
        id: "ares.firestorm-wall",
        description: "Firestorm wall linking, contact effects, charge feedback, and projectile interception",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresFirestorm.test.ts"],
        notes: "Firestorm.Wall, SubjectToFirestorm, and IgnoresFirestorm are normalized. Same-owner four-way links, active hostile projectile interception along the full projectile path, direct-contact immolation, and damage-to-active-charge feedback follow the Antares 3.0p1 semantics. Persistent superweapon state, active/idle wall animation presentation, and trigger/network action coverage remain open.",
    },
    {
        id: "ares.superweapon-battery",
        description: "Antares Battery charge-drain power and building-state effects",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresBattery.test.ts", "AresSuperWeaponChargeDrain.test.ts"],
        notes: "Battery.Power, Battery.KeepOnline, Battery.Overpower, duplicate-preserving activation/deactivation, low-power radar retention, and charge-drain lifecycle are wired from Antares 3.0p1 semantics. Full sidebar/action, AI, save/load, and network presentation remain open.",
    },
    {
        id: "ares.superweapon-hunter-seeker",
        description: "Antares Hunter Seeker launch, target acquisition, pursuit, and detonation",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresHunterSeeker.test.ts"],
        notes: "Per-superweapon/side/global launch configuration, deterministic eligible-building selection, data-defined aircraft launch, enemy target acquisition, pursuit, and weapon/warhead detonation are wired. Native-lepton proximity thresholds and shared emerge/ascent/descent speeds are consumed by the common aircraft locomotor. Specialized target preference edge cases, AI auto-fire, full presentation parity, and in-flight persistence remain open.",
    },
    {
        id: "ares.superweapon-deferment",
        description: "Ares SW.Deferment delay for supported superweapon state machines",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponDeferment.test.ts"],
        notes: "Per-superweapon deferment overrides the Lightning Storm and Psychic Dominator pre-effect delays; UnitDelivery already uses the same field with its documented default. Other types intentionally do not consume SW.Deferment because Antares does not apply it to them.",
    },
    {
        id: "ares.superweapon-post-dependent",
        description: "Ares SW.PostDependent second-stage superweapon selection",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponPostDependent.test.ts", "AresChronoWarp.test.ts"],
        notes: "The authored dependent ID is resolved case-insensitively, with the first authored ChronoWarp fallback for ChronoSphere; the generic action path records the source and lets the dependent ChronoWarp supply the destination. Full dependent-graph coverage, cursor/presentation resources, AI, persistence, target-content, and multiplayer certification remain open.",
    },
    {
        id: "ares.superweapon-radar-event",
        description: "Ares SW.CreateRadarEvent launch notifications",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponRadar.test.ts"],
        notes: "Explicit CreateRadarEvent launches notify every combatant through RadarTrait, preserving host suppression/duration rules; full-map SonarPulse remains exempt from its local radar event path.",
    },
    {
        id: "ares.superweapon-ai-targeting",
        description: "Ares SW.AITargeting modes and AI-required target defaults",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponAITargeting.test.ts", "AresSuperWeaponAIHost.test.ts"],
        notes: "Documented modes, SW.AutoFire routing, offensive/defensive preferred-cell selection, cloaked-target exclusion for the offensive Ares modes, shared provider-range/designator/inhibitor filtering, inactive LightningStorm/Dominator constraints, AI-required house and land/water/content masks, ThreatPosed MultiMissile scoring, true no-target/LightningRandom behavior, HunterSeeker favorite-enemy gating, EMPulse cannon reachability/TargetSelf, UnitDelivery landing-area selection, and DropPod outer-sector selection are consumed by the built-in AI host. Iron Curtain waits for team-script activation and ForceShield only responds through the defense path; manual UseAITargeting flow, presentation, persistence, and multiplayer certification remain open.",
    },
    {
        id: "ares.superweapon-money",
        description: "Ares superweapon launch-time Money.Amount transactions",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponMoney.test.ts"],
        notes: "Money.Amount is validated before charge consumption and applied once after launch acceptance; recurring Money.DrainAmount/DrainDelay are tracked by the separate charge-drain capability.",
    },
    {
        id: "ares.superweapon-range",
        description: "Ares superweapon area selection and launch-site range/designator/inhibitor gates",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeaponRange.test.ts", "AresSuperWeaponTargeting.test.ts"],
        notes: "A generic Antares-compatible cell resolver is shared with SonarPulse and explicit SW.Range is consumed by Psychic Dominator, Genetic Mutator, Force Shield, Psychic Reveal, ChronoSphere, and Lightning Storm. The common activation path now enforces SW.RangeMinimum/Maximum against operational providers, SW.Designators/SW.AnyDesignator against owned TechnoTypes, and SW.Inhibitors/SW.AnyInhibitor against enemy target areas; effect-specific range coverage, AI presentation, persistence, and multiplayer certification remain open.",
    },
    {
        id: "ares.superweapon-unit-delivery",
        description: "UnitDelivery creates data-defined TechnoTypes near the target cell",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSuperWeapons.test.ts", "AresUnitDelivery.test.ts"],
        notes: "Verified against the Ares UnitDelivery documentation and Antares 3.0p1 state machine: deferred placement, owner selection, infantry/vehicle/aircraft/building delivery, irregular foundation bounds, BaseNormal override, and deterministic cleanup are covered; buildup/audio/power edge behavior remains separate.",
    },
    {
        id: "ares.superweapon-sonar-pulse",
        description: "SonarPulse temporarily decloaks eligible technos in a water-targeted area",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresSonarPulse.test.ts", "AresSuperWeapons.test.ts"],
        notes: "Verified against Ares 3.0p1/Antares: default radius and enemy-water targeting, full-map mode, rectangular/circular range selection, and max-duration cloak suppression are wired; explicit radar-event presentation remains dependent on the host radar event table.",
    },
    {
        id: "ares.superweapon-empulse",
        description: "EMPulse selects powered EMP cannons and delivers their EMP warhead",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresEMPulse.test.ts", "AresSuperWeapons.test.ts"],
        notes: "Antares launch-site defaults, EMPulse.Cannons override, linked range behavior, SW.MaxCount, TargetSelf immediate detonation, PulseDelay-backed normal firing, and PulseBall default/none/custom animation at the authored weapon FLH are wired; complete AI selector parity and multiplayer/save certification remain separate.",
    },
    {
        id: "ares.superweapon-drop-pod",
        description: "DropPod selects and places data-defined non-building TechnoTypes",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresDropPod.test.ts", "AresSuperWeapons.test.ts"],
        notes: "Antares 3.0p1 global/per-superweapon infantry type lists, inclusive count range, deterministic type selection, valid landing placement, ownership, fractional veterancy, cleanup, default/custom trailer animation, and optional landing impact weapon are wired. Full in-flight DropPod locomotion, AI targeting, and persistent in-flight state remain open.",
    },
    {
        id: "ares.staged-weapons",
        description: "Data-defined weapon stages, spin-up, and burst behavior",
        implemented: false,
        parserImplemented: false,
        runtimeImplemented: false,
        tests: [],
    },
    {
        id: "ares.projectile-extensions",
        description: "Extended projectile trajectories, splits, and airburst behavior",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresProjectileExtensions.test.ts"],
        notes: "ProjectileRules now preserves Proximity, Airburst/AirburstWeapon, Cluster, AirburstSpread, AroundTarget, Splits, RetargetAccuracy, RetargetSelf, and AttachedSystem. Airburst cell fan-out and Splits target retargeting use deterministic native child projectiles with Antares defaults; documented smoke-only AttachedSystem definitions resolve the authored ParticleSystem -> Particle -> Image chain and follow projectile movement; full Proximity edge parity, non-smoke particle behavior, and projectile trajectory extensions beyond this MO-required slice remain open.",
    },
    {
        id: "ares.custom-animation-palettes",
        description: "Custom animation and projectile palette selection",
        implemented: true,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresCustomPalette.test.ts"],
        notes: "ObjectArt reads CustomPalette for animations/projectiles; Theater resolves complete .pal names and Ares's first ~~~ theater substitution while preserving legacy Palette= basename fallback.",
    },
    {
        id: "ares.passenger-extensions",
        description: "Extended passenger, consumption, and open-topped behavior",
        implemented: false,
        parserImplemented: false,
        runtimeImplemented: false,
        tests: [],
    },
    {
        id: "ares.status-effects",
        description: "Generic attach/status effects used by extension content",
        implemented: false,
        parserImplemented: true,
        runtimeImplemented: true,
        tests: ["AresAttachEffect.test.ts", "AresAttachEffectRuntime.test.ts", "AresAttachEffectTraitBridge.test.ts", "AresAttachEffectObjectFactory.test.ts", "AresAttachEffectCombat.test.ts", "AresAttachEffectCombatCallsites.test.ts", "AresAnimationDamage.test.ts", "AresCompatibilityScanner.test.ts"],
        notes: "The documented AttachEffect fields are normalized for TechnoType and Warhead sections; ObjectFactory registration and a generic trait cover automatic TechnoType spawn timing, renewal, protection retry, effect instances, reapplication/stacking decisions, expiry, entry discard, aggregate numeric modifiers, and the generic combat callsites apply effective Speed/Armor/Firepower/ROF decisions. AttachEffect.Cloakable now grants a temporary cloak source and decloaks safely when the last source expires without removing permanent/veteran cloaking. Authored animations now attach to every techno renderable, loop with the unit, and are removed/recreated across cloak and TemporalHidesAnim transitions. Their Ares Damage, Damage.Delay, Warhead, and Weapon fields now run through the shared Warhead detonation path for attached effects. Standalone TriggerAnim and WarheadDetonate animation instances now use the same deterministic frame clock and area detonation bridge. Full transport/temporal state replay, save/load, AI, and deterministic multiplayer replay remain open.",
    },
    {
        id: "ares.unknown-key",
        description: "An extension-like key with no registered semantics",
        implemented: false,
        parserImplemented: false,
        runtimeImplemented: false,
        tests: [],
    },
];

export class AresFeatureRegistry {
    private readonly features = new Map<string, ExtensionFeature>();

    constructor(features: readonly ExtensionFeature[] = DEFAULT_ARES_FEATURES) {
        for (const feature of features) {
            this.register(feature);
        }
    }

    register(feature: ExtensionFeature): void {
        this.features.set(feature.id, {
            ...feature,
            tests: [...feature.tests],
        });
    }

    get(id: string): ExtensionFeature | undefined {
        const feature = this.features.get(id);
        return feature ? { ...feature, tests: [...feature.tests] } : undefined;
    }

    list(): ExtensionFeature[] {
        return [...this.features.values()].map((feature) => ({
            ...feature,
            tests: [...feature.tests],
        }));
    }

    has(id: string): boolean {
        return this.features.has(id);
    }
}

export function createDefaultAresFeatureRegistry(): AresFeatureRegistry {
    return new AresFeatureRegistry();
}
